### ISSUE TITLE
z not installed on setup

### ISSUE THREAD

**Issue by christippett** [jthegedus/dotfiles#18]
**Describe the bug**
z.sh not installed on setup.

**Steps to reproduce**
Run `wget -O https://raw.githubusercontent.com/rupa/z/master/z.sh "${HOME}"` (snippet from `setup-devtools.bash`)

**Expected behavior**
Downloads `z.sh` to home directory.

**Screenshots**
NA

**Additional context**
NA

**Comment by jthegedus** [comment]
Good find, cheers!
