### ISSUE TITLE
Move z.sh and fzf into setup-shell.bash

### ISSUE THREAD

**Issue by christippett** [jthegedus/dotfiles#20]
Would you consider moving the installation steps for `z.sh` and `fzf` into `setup-shell.bash`?

For setting up non-development environments (in my case, a home server), it'd be great to still install all the nice shell utilities by running `setup-shell.bash`.

**Comment by jthegedus** [comment]
Yes, yes I would. They are more shell-y than dev-y. I can address this tomorrow evening unless you need it sooner, in which case, PR?

**Comment by christippett** [comment]
Excellent, raised a PR. Loving your dotfiles by the way, so much simpler than what I was originally using. Starship is beautiful.
