### ISSUE TITLE
Use Brewfile for installing packages on MacOS

### ISSUE THREAD

**Issue by christippett** [jthegedus/dotfiles#22]
**Is your feature request related to a problem? Please describe.**
Homebrew allows you to declare which packages (including casks) you'd like installed in a [Brewfile](https://github.com/Homebrew/homebrew-bundle). Rather than peppering the install scripts with `brew install`'s, desired packages could be listed in a `Brewfile` that's committed to the repository and then referenced as part of the install process. This would allow users to customise their environments by editing a single resource, instead of inspecting and modifying the underlying scripts.

**Describe the solution you'd like**
Add a step within `setup-devtools.bash` to call `brew bundle --global` and install any and all packages listed in the user's `Brewfile` located in their home directory. This `Brewfile` would be symlinked from a version sourced from the dotfiles repository (`config/Brewfile`).

**Describe alternatives you've considered**
Keep the status quo and install relevant packages inline within the install scripts.

**Additional context**
NA

**Comment by jthegedus** [comment]
I only recently learnt about brewfiles and expected it to be a large refactor so didn't look into it. I like how easy this is as I do want to keep these dotfiles fairly simple compared to the others out there. Thanks
