### ISSUE TITLE
Include other configuration files in dotfiles repository

### ISSUE THREAD

**Issue by christippett** [jthegedus/dotfiles#23]
**Is your feature request related to a problem? Please describe.**
Some configuration files make sense to be replicated across different environments. A user's dotfiles repository is a good place to save and instantiate these, rather than having to employ a manual process separate to the shell/application setup to copy these across.

Some examples include a user's `.gitconfig`, `.vimrc`,  `ssh/config` file, etc.

**Describe the solution you'd like**
One potential approach is to have the shell setup script loop through each file included in the `config/` directory, symlinking each file it finds into the user's `$HOME` directory. It should traverse sub-folders, so configuration files like `.ssh/config` are supported.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by jthegedus** [comment]
Thanks for the addition.
